#!/usr/bin/env bash
# 生成 /etc/asound.conf, 配置 Orange Pi Zero3 音频路由
#
# Orange Pi Zero3 官方参数 (13Pin 2 出 1 入):
#   输出模式 (output_mode):
#     auto    : 优先板载 3.5mm (sndh618/H616Audio/audiocodec) > USB > HDMI
#     onboard : 强制 13Pin 板载耳机口 (零硬件成本, 推荐)
#     usb     : 强制 USB 声卡 / USB 音箱
#     hdmi    : HDMI 音频 (占 HDMI 资源, 不推荐)
#     hw:X,Y  : 直接指定 ALSA 设备
#
#   输入模式 (input_mode):
#     auto    : 优先 USB 麦 > 板载 13Pin 麦 (H618 codec 内置 ADC)
#     usb     : 强制 USB 麦克风 (推荐, 灵敏度高)
#     onboard : 强制 13Pin 板载麦 (零 USB 占用, 灵敏度一般, 需焊 13Pin)
#     hw:X,Y  : 直接指定 ALSA 设备
#
# 用法:
#   sudo bash scripts/setup_alsa.sh                                  # 用 config 里的 mode
#   sudo OUTPUT_MODE=onboard INPUT_MODE=onboard bash scripts/setup_alsa.sh
#   sudo OUTPUT_MODE=usb INPUT_MODE=usb bash scripts/setup_alsa.sh

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "请使用 sudo"
  exit 1
fi

ASOUND="/etc/asound.conf"
UDEV="/etc/udev/rules.d/99-usb-audio.rules"

# 默认模式 (可被环境变量覆盖)
OUTPUT_MODE="${OUTPUT_MODE:-auto}"
INPUT_MODE="${INPUT_MODE:-auto}"

# 也可从 config.json 读取
if [[ -f /opt/music-player/config/config.json ]]; then
  CFG_OUT=$(python3 -c "import json; print(json.load(open('/opt/music-player/config/config.json')).get('audio',{}).get('output_mode','auto'))" 2>/dev/null || echo "")
  CFG_IN=$(python3 -c "import json; print(json.load(open('/opt/music-player/config/config.json')).get('audio',{}).get('input_mode','auto'))" 2>/dev/null || echo "")
  [[ -n "$CFG_OUT" && "$OUTPUT_MODE" == "auto" ]] && OUTPUT_MODE="$CFG_OUT"
  [[ -n "$CFG_IN"  && "$INPUT_MODE"  == "auto" ]] && INPUT_MODE="$CFG_IN"
fi

echo "==> 枚举 ALSA 设备"
if ! command -v arecord &>/dev/null || ! command -v aplay &>/dev/null; then
  echo "未安装 alsa-utils"
  exit 1
fi

echo "  --- aplay -l (output) ---"
aplay -l 2>/dev/null || true
echo "  --- arecord -l (input) ---"
arecord -l 2>/dev/null || true
echo

# ──────────── 辅助函数: 取 card index ────────────

# 解析 aplay -l / arecord -l 输出, 返回包含关键字的所有 card 列表
_cards_matching() {
  local kind="$1" pat="$2"
  local cmd
  if [[ "$kind" == "playback" ]]; then
    cmd="aplay"
  else
    cmd="arecord"
  fi
  "$cmd" -l 2>/dev/null | awk -v pat="$pat" '
    /card [0-9]+:/ {
      match($0, /card ([0-9]+):/, m)
      if (m[1] != "" && $0 ~ pat) {
        print m[1]
      }
    }'
}

# 取第一块指定类型的 card
_first_card() {
  local kind="$1" pat="$2"
  _cards_matching "$kind" "$pat" | head -1
}

# 板载 codec 关键字 (H618 内置 codec, 13Pin 2 出 1 入)
# 包含常见的 H618 / H616 / Allwinner / sunxi / cdc pcm / audiocodec
_ONBOARD_RE='sndh618\|H616Audio\|h616-audio\|audiocodec\|sun50i-h616\|allwinner-h616\|allwinner-codec\|sunxi-sndac108\|sndac108\|es8388\|1c22800\|snd-sunxi\|cdc pcm'

# 输出卡选择
_select_output_card() {
  local mode="$1"
  case "$mode" in
    auto)
      local onboard
      onboard=$(_first_card playback "$_ONBOARD_RE")
      if [[ -n "$onboard" ]]; then
        echo "$onboard"
        return
      fi
      local usb
      usb=$(_first_card playback 'USB\|usb')
      if [[ -n "$usb" ]]; then
        echo "$usb"
        return
      fi
      local hdmi
      hdmi=$(_first_card playback 'hdmi\|HDMI')
      if [[ -n "$hdmi" ]]; then
        echo "$hdmi"
        return
      fi
      _first_card playback 'card'
      ;;
    onboard)
      _first_card playback "$_ONBOARD_RE"
      ;;
    usb)
      _first_card playback 'USB\|usb'
      ;;
    hdmi)
      _first_card playback 'hdmi\|HDMI'
      ;;
    hw:*)
      echo "$mode" | sed -nE 's/hw:([0-9]+),.*/\1/p'
      ;;
    *)
      echo ""
      ;;
  esac
}

# 输入卡选择 (auto: USB 麦 > 13Pin 板载麦)
_select_input_card() {
  local mode="$1"
  case "$mode" in
    auto)
      # 优先 USB 麦 (灵敏度高, 抗噪好, 推荐)
      local usb
      usb=$(_first_card capture 'USB\|usb')
      if [[ -n "$usb" ]]; then
        echo "$usb"
        return
      fi
      # 否则回退到 13Pin 板载麦 (H618 codec ADC)
      local onboard
      onboard=$(_first_card capture "$_ONBOARD_RE")
      if [[ -n "$onboard" ]]; then
        echo "$onboard"
        return
      fi
      # 实在没有, 退回首块
      _first_card capture 'card'
      ;;
    usb)
      _first_card capture 'USB\|usb'
      ;;
    onboard)
      _first_card capture "$_ONBOARD_RE"
      ;;
    hw:*)
      echo "$mode" | sed -nE 's/hw:([0-9]+),.*/\1/p'
      ;;
    *)
      echo ""
      ;;
  esac
}

_hw_str() {
  local card="$1" subdev="${2:-0}"
  echo "hw:${card},${subdev}"
}

OUT_CARD=$(_select_output_card "$OUTPUT_MODE")
IN_CARD=$(_select_input_card "$INPUT_MODE")

OUT_DEV=$(_hw_str "${OUT_CARD:-0}")
IN_DEV=$(_hw_str "${IN_CARD:-0}")

echo "==> 选择结果"
echo "  output mode: ${OUTPUT_MODE}  →  card=${OUT_CARD:-0}  (${OUT_DEV})"
echo "  input  mode: ${INPUT_MODE}   →  card=${IN_CARD:-0}  (${IN_DEV})"

# 写 /etc/asound.conf
cat > "$ASOUND" <<EOF
# Generated by opi-music-player setup_alsa.sh
# output_mode=${OUTPUT_MODE}, input_mode=${INPUT_MODE}
#
# Orange Pi Zero3 官方接口 (13Pin 2 出 1 入):
#   - 1×USB-A 2.0 + 1×Type-C(5V/3A电源)
#   - 13Pin: 2×USB 2.0 + 3.5mm耳机(L/R) + MIC(3.5mm) + TV-Out + IR
#   - 26Pin GPIO (无标准功能)
# 推荐配置 (13Pin 全套, 零 USB 占用):
#   - 13Pin 板载麦 → 语音输入
#   - 13Pin 板载耳机口 → 喇叭
#   - USB-A → 调试/U盘
# 备选 (USB 方案, 不需焊 13Pin):
#   - USB 麦 → 语音输入
#   - USB 音箱 → 播放输出

pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "${OUT_DEV}"
    }
    capture.pcm {
        type plug
        slave.pcm "${IN_DEV}"
    }
}

ctl.!default {
    type hw
    card ${OUT_CARD:-0}
}
EOF
echo "  wrote $ASOUND"

# udev 规则: 给 USB 声卡/麦固定命名
cat > "$UDEV" <<'EOF'
# OPI Music Player: 给 USB 声卡/麦克风起固定名字
# 优先用 idVendor/idProduct 匹配, 避免插拔后 card index 漂移
KERNEL=="controlC[0-9]*", SUBSYSTEM=="sound", ATTRS{idVendor}=="*", ENV{SOUND_ID}="usb"
EOF

udevadm control --reload-rules 2>/dev/null || true
echo "  wrote $UDEV"

echo "==> 完成"
echo "  验证 mic: arecord -d 3 -f S16_LE -r 16000 -c 1 /tmp/test_mic.wav"
echo "  验证输出: aplay /tmp/test_mic.wav"
echo "  调音量: alsamixer (按 F6 选卡)"
